mysql:
  host: 127.0.0.1
  port: 3306
  db: frozen_throne
  user: root
  password: Whosyourdaddy1993!
  log_level: dev
logger:
  level: info
  file_name: './logs/server.log'
  max_size: 1
  max_age: 30
  max_backup: 5
system:
  host: "0.0.0.0"
  port: 8888
  env: release
